pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // Adds the repository where the RTSP server engine is hosted
        maven { url 'https://jitpack.io' }
    }
}

rootProject.name = "ScreenStream"
include ':app'
